export const LOGIN_ACTION_KEY = "LOGIN_ACTION_KEY";
export const LOGOUT_ACTION_KEY = "LOGOUT_ACTION_KEY";
export const ADD_PRODUCT_ACTION_KEY = "ADD_PRODUCT_ACTION_KEY";
export const EDIT_PRODUCT_ACTION_KEY = "EDIT_PRODUCT_ACTION_KEY";
